const KEY='ms-content-studio-v1';
const seed=[{id:'a1',type:'article',title:'لماذا لا يكفي انخفاض الـCPA للحكم على نجاح حملتك؟',excerpt:'قراءة أعمق لجودة النمو.',body:'التكلفة مؤشر مهم، لكنها لا تخبرك وحدها إن كنت تبني نموًا مربحًا.\n\nاربط تكلفة الاكتساب بجودة التحويل وهامش الربح وقيمة العميل.',status:'published',category:'إعلانات ممولة',slug:'cpa-is-not-enough',seo:'طريقة تقييم تكلفة الاكتساب داخل الحملات الإعلانية بصورة صحيحة.',updated:'2026-09-05'},{id:'c1',type:'case-study',title:'Shiddah Fitness — رحلة عميل موحدة',excerpt:'ربط الحملات بالبيانات وسلوك الشراء.',body:'التحدي\nكانت البيانات موزعة بين المتجر ومنصات الإعلانات وأدوات القياس.\n\nالمنهج\nتحديد الأحداث الأساسية ورسم مصادر البيانات ونقاط انتقال العميل.',status:'draft',category:'تحليل أداء',slug:'shiddah-fitness',seo:'دراسة حالة عن توحيد رحلة العميل وربط بيانات الحملات.',updated:'2026-09-05'}];
let items=JSON.parse(localStorage.getItem(KEY)||'null')||seed;let editId=null;let currentView='overview';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function persist(){localStorage.setItem(KEY,JSON.stringify(items));render()}
function typeLabel(t){return t==='article'?'مقال':'دراسة حالة'}function statusLabel(s){return s==='published'?'منشور':'مسودة'}
function render(){const articles=items.filter(i=>i.type==='article'),cases=items.filter(i=>i.type==='case-study');$('#articleCount').textContent=articles.length;$('#caseCount').textContent=cases.length;$('#totalCount').textContent=items.length;$('#publishedCount').textContent=items.filter(i=>i.status==='published').length;$('#draftCount').textContent=items.filter(i=>i.status==='draft').length;const row=i=>`<div class="content-item"><span class="content-icon">${i.type==='article'?'▤':'◫'}</span><div><b>${escapeHtml(i.title)}</b><small>${typeLabel(i.type)} · ${escapeHtml(i.category)} · ${i.updated}</small></div><span class="badge ${i.status}">${statusLabel(i.status)}</span></div>`;$('#recentList').innerHTML=items.slice().reverse().slice(0,5).map(row).join('')||'<div class="empty-list">لا يوجد محتوى بعد</div>';renderLibrary()}
function renderLibrary(){let list=items.filter(i=>currentView==='articles'?i.type==='article':currentView==='cases'?i.type==='case-study':true);const q=($('#searchInput')?.value||'').trim().toLowerCase(),s=$('#statusFilter')?.value||'all';list=list.filter(i=>(!q||i.title.toLowerCase().includes(q))&&(s==='all'||i.status===s));$('#libraryList').innerHTML=list.map(i=>`<div class="table-row"><div><b>${escapeHtml(i.title)}</b><small>${escapeHtml(i.slug)}</small></div><span>${typeLabel(i.type)}</span><span class="badge ${i.status}">${statusLabel(i.status)}</span><div class="row-actions"><button class="icon-btn" data-edit="${i.id}" aria-label="تعديل">✎</button><button class="icon-btn" data-delete="${i.id}" aria-label="حذف">×</button></div></div>`).join('')||'<div class="empty-list">لا توجد نتائج</div>'}
function setView(view){currentView=view;$$('.view').forEach(v=>v.classList.remove('active'));$$('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='overview'){$('#overviewView').classList.add('active');$('#viewTitle').textContent='نظرة عامة'}else if(view==='media'){$('#mediaView').classList.add('active');$('#viewTitle').textContent='مكتبة الوسائط'}else{$('#libraryView').classList.add('active');$('#viewTitle').textContent=view==='articles'?'المقالات':'دراسات الحالة';renderLibrary()}$('.sidebar').classList.remove('open')}
function openEditor(type='article',id=null){editId=id;const i=id?items.find(x=>x.id===id):null;$('#editorKicker').textContent=i?'تعديل المحتوى':'محتوى جديد';$('#editorTitle').textContent=i?i.title:'إنشاء محتوى';$('#contentTitle').value=i?.title||'';$('#contentExcerpt').value=i?.excerpt||'';$('#contentBody').value=i?.body||'';$('#contentType').value=i?.type||type;$('#contentStatus').value=i?.status||'draft';$('#contentCategory').value=i?.category||'إعلانات ممولة';$('#contentSlug').value=i?.slug||'';$('#contentSeo').value=i?.seo||'';$('#seoCount').textContent=(i?.seo||'').length;$('#coverPreview').textContent=i?.coverName||'لا توجد صورة';$('#saveStatus').textContent='';$('#editorDialog').showModal()}
function collect(status){const title=$('#contentTitle').value.trim();if(!title){$('#saveStatus').textContent='أضف العنوان أولًا';return null}return{id:editId||String(Date.now()),type:$('#contentType').value,title,excerpt:$('#contentExcerpt').value.trim(),body:$('#contentBody').value.trim(),status:status||$('#contentStatus').value,category:$('#contentCategory').value,slug:$('#contentSlug').value.trim()||slugify(title),seo:$('#contentSeo').value.trim(),coverName:$('#coverImage').files[0]?.name||'',updated:new Date().toISOString().slice(0,10)}}
function save(status){const item=collect(status);if(!item)return;const idx=items.findIndex(i=>i.id===item.id);if(idx>=0)items[idx]=item;else items.push(item);persist();$('#editorDialog').close()}
function preview(){const i=collect();if(!i)return;$('#previewContent').innerHTML=`<div class="badge ${i.status}">${statusLabel(i.status)}</div><h1>${escapeHtml(i.title)}</h1><p>${escapeHtml(i.excerpt)}</p><hr style="border-color:#252d39"><p>${escapeHtml(i.body)}</p>`;$('#previewDialog').showModal()}
function exportContent(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),content:items},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mohamed-sherif-content.json';a.click();URL.revokeObjectURL(a.href)}
function slugify(s){return s.toLowerCase().trim().replace(/[\s_]+/g,'-').replace(/[^\u0600-\u06FFa-z0-9-]/g,'').replace(/-+/g,'-')}
function escapeHtml(s=''){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
$$('.side-link').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));$$('[data-type]').forEach(b=>b.onclick=()=>openEditor(b.dataset.type));$('#newContent').onclick=()=>openEditor();$('#exportAll').onclick=exportContent;$('#saveDraft').onclick=()=>save('draft');$('#previewBtn').onclick=preview;$('#editorForm').onsubmit=e=>{e.preventDefault();save()};$('#contentSeo').oninput=e=>$('#seoCount').textContent=e.target.value.length;$('#contentTitle').oninput=e=>{if(!editId)$('#contentSlug').value=slugify(e.target.value)};$('#coverImage').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#coverPreview').textContent=f.name;const r=new FileReader;r.onload=()=>{$('#coverPreview').style.backgroundImage=`url(${r.result})`;$('#coverPreview').textContent=''};r.readAsDataURL(f)};$('#searchInput').oninput=renderLibrary;$('#statusFilter').onchange=renderLibrary;$('#libraryList').onclick=e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit)openEditor(null,edit);if(del&&confirm('حذف هذا المحتوى؟')){items=items.filter(i=>i.id!==del);persist()}};$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');render();
